openapi: 3.0.0
info:
  title: Email Collection API
  version: 1.0.0
  description: API to collect email addresses with user consent.
paths:
  /collect_email:
    post:
      summary: Collect an email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                consent:
                  type: boolean
                  example: true
      responses:
        '200':
          description: Email collected successfully
        '400':
          description: Invalid request
